name: finance_tracker
description: "MoneyFlow - Ứng dụng quản lý tài chính cá nhân thông minh"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # Database
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # Local Storage
  shared_preferences: ^2.2.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  
  # UI/UX
  fl_chart: ^0.63.0
  intl: ^0.18.0
  flutter_slidable: ^3.0.1
  
  # Utilities
  uuid: ^4.5.1
  equatable: ^2.0.5
  collection: ^1.18.0
  
  # Pull to refresh
  pull_to_refresh: ^2.0.0
  
  # Notifications (temporarily disabled)
  # flutter_local_notifications: ^17.2.2
  # permission_handler: ^11.3.1
  
  # Icons
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  
  # Image picker
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.13.0
  
  # App Icon & Splash Screen
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

# Configuration for flutter_native_splash
flutter_native_splash:
  color: "#2196F3"
  image: assets/icons/app_icon.png
  color_dark: "#1976D2"
  image_dark: assets/icons/app_icon.png
  android: true
  ios: true
  web: true